[project]
name = "classresults"
version = "0.2.5"
description = ""
authors = [
    {name = "Thomas BOBEE",email = "thomasbobe3@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.14,<4.0"
dependencies = [
    "requests (>=2.34.2,<3.0.0)",
    "setuptools (>=80.0.0,<81.0.0)",
    "xlsxwriter (>=3.2.9,<4.0.0)",
    "click (>=8.5.0,<9.0.0)",
    "poulpy @ https://gitlab.cri.epita.fr/api/v4/projects/8706/packages/pypi/files/9a85510688cadb175346ae0e3012d97123bfe9c5a91b99429f28fa9b54dc916d/poulpy-1.2.13.tar.gz#sha256=9a85510688cadb175346ae0e3012d97123bfe9c5a91b99429f28fa9b54dc916d"
]

[tool.poetry.scripts]
classresults = "classresults:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
