[project]
name = "classresults"
version = ["version"]
description = ""
authors = [
    {name = "Thomas BOBEE",email = "thomasbobe3@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests (>=2.34.2,<3.0.0)",
    "setuptools (>=80.0.0,<81.0.0)",
    "xlsxwriter (>=3.2.9,<4.0.0)"
]

[tool.poetry.scripts]
classresults = "classresults:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
